apiVersion: v1
kind: ConfigMap
metadata:
  name: storelense-config
  namespace: storelense
data:
  DB_HOST:                postgres
  DB_PORT:                "5432"
  DB_NAME:                storelense
  DB_USERNAME:            storelense_app
  REDIS_HOST:             redis
  REDIS_PORT:             "6379"
  KAFKA_BOOTSTRAP:        kafka:9092
  PRODUCT_SERVICE_URL:    http://product-service:8083
  STORE_SERVICE_URL:      http://store-service:8082
  ERP_PUSH_SOH_ENABLED:   "false"
  ERP_API_VERSION:        v1
